
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:9 (project)"
    message: |
      The system is: Linux - 6.8.0-49-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/chaikney/code/Cube_3d/MLX42/CMakeFiles/3.27.6/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/c++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/chaikney/code/Cube_3d/MLX42/CMakeFiles/3.27.6/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-FPqR5X"
      binary: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-FPqR5X"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-FPqR5X'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_b6177/fast
        No such file or directory
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Check for working C compiler: /usr/bin/cc"
    directories:
      source: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-CT2x7M"
      binary: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-CT2x7M"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-CT2x7M'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_103bf/fast
        No such file or directory
        
      exitCode: 1
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/chaikney/code/Cube_3d/MLX42/CMakeFiles/3.27.6/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/c++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/chaikney/code/Cube_3d/MLX42/CMakeFiles/3.27.6/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-2QKejW"
      binary: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-2QKejW"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-2QKejW'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_45023/fast
        No such file or directory
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Check for working C compiler: /usr/bin/cc"
    directories:
      source: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-0N3NdJ"
      binary: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-0N3NdJ"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-0N3NdJ'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_3894c/fast
        No such file or directory
        
      exitCode: 1
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/chaikney/code/Cube_3d/MLX42/CMakeFiles/3.27.6/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/c++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/chaikney/code/Cube_3d/MLX42/CMakeFiles/3.27.6/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-rqzA7G"
      binary: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-rqzA7G"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-rqzA7G'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_30653/fast
        No such file or directory
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Check for working C compiler: /usr/bin/cc"
    directories:
      source: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-ugU2tH"
      binary: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-ugU2tH"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-ugU2tH'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_a5251/fast
        No such file or directory
        
      exitCode: 1
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/chaikney/code/Cube_3d/MLX42/CMakeFiles/3.27.6/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/c++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/chaikney/code/Cube_3d/MLX42/CMakeFiles/3.27.6/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-ZV0v05"
      binary: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-ZV0v05"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-ZV0v05'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_35a10/fast
        No such file or directory
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Check for working C compiler: /usr/bin/cc"
    directories:
      source: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-hm17JE"
      binary: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-hm17JE"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-hm17JE'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_6bf93/fast
        No such file or directory
        
      exitCode: 1
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/chaikney/code/Cube_3d/MLX42/CMakeFiles/3.27.6/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/c++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/chaikney/code/Cube_3d/MLX42/CMakeFiles/3.27.6/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-qCH6nR"
      binary: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-qCH6nR"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-qCH6nR'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_0a0a3/fast
        No such file or directory
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Check for working C compiler: /usr/bin/cc"
    directories:
      source: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-xWVZEM"
      binary: "/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-xWVZEM"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/chaikney/code/Cube_3d/MLX42/CMakeFiles/CMakeScratch/TryCompile-xWVZEM'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_b3bb1/fast
        No such file or directory
        
      exitCode: 1
...
